### ISSUE TITLE
Perhaps this should not belong in ros-melodic-arch?

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-fcl#1]
Not sure how to interpret [this](http://wiki.ros.org/fcl):

>Starting with ROS Groovy, this is no longer a ROS package, but a standalone library. Please see >https://github.com/flexible-collision-library

I had to double check exactly what defines a ROS package:

>A ROS package is simply a directory descended from ROS_PACKAGE_PATH (see ROS Environment Variables) that has a package.xml file in it.

This package has no `package.xml`. So, this might be *useful* for ROS, but is not technically a ROS package. I view it as something like opencv. Auxiliary and used (as perhaps both a dep and make dep), but not a ROS package in and of itself.

I ran into this because I was looking up which packages have wiki pages from the list of ROS pacakges [here](http://repositories.ros.org/rosdistro_cache/). This package had no entry there, so I checked and discovered the above. In other words, ROS also doesn't consider this as belonging to ROS.

**Comment by acxz** [comment]
I agree. I do not think there should be a `ros-melodic-fcl` package. Looking at packages that depend on it, `ros-melodic-moveit-core`, the kinetic version actually depends on the `fcl` package instead of the ros version of fcl.

**Comment by jwhendy** [comment]
Just ran into this again, as I had some time to putz on my scripts to update the rest of ros-melodic-arch to the github sources. I went to look it up in the distribution.yaml and it wasn't there.

Not sure how to treat this... it still will be a dependency of ROS packages, it's just not in the ROS official ecosystem any longer.

@bionade24 any thoughts on what best to do? Move this into AUR, but drop the `ros-melodic-*` prefix?

**Comment by bionade24** [comment]
If so, yes. Just add the `replaces=` and `provides=` arguments then. I'll delete the package then.

**Comment by acxz** [comment]
I do not understand by what you mean by adding the `replaces=` and `provides=` arguments? Do you mean any packages that depend on this package should be fixed before we delete this one?

**Comment by bionade24** [comment]
No, this are the package attributes that we don't need to do that and won't have problems. https://wiki.archlinux.org/index.php/PKGBUILD#replaces

**Comment by acxz** [comment]
So from what I understand you are saying we should add `replaces=('ros-melodic-fcl`) to the `fcl` package?

**Comment by bionade24** [comment]
And `conflicts=(''ros-melodic-fcl'), too. Otherwise we'll have FS conflicts.

**Comment by acxz** [comment]
How would we convince `fcl`'s maintainer to add these tags tho? I don't `fcl` should care at all about what `ros-melodic-fcl` does.

**Comment by acxz** [comment]
In any case, I have submitted a PR https://github.com/ros-melodic-arch/ros-melodic-moveit-core/pull/2 that removes the dependency of ros-melodic-fcl for the only package in the AUR that depends on it (moveit-core)

**Comment by bionade24** [comment]
You need `replaces` and `conflicts` anyway. Otherwise pacman wents crazy.

**Comment by acxz** [comment]
It seems like this package has been removed from the AUR, can this repo be deleted? @bionade24

**Comment by bionade24** [comment]
I'll archive it as I did with other deprecated repos. Last time the ompl maintainer probably wouldn't have patched it if I hadn't given him the link to our old repo with the patch. Thx for reminding me of doing this.
